while True:
    print('You got stuck in an infinite loop. Haha')
    print('...')
    print('...')
    print('...')
    print('...')
    print('...')
    print('Not so funny now though')
    print('...')
    print('...')
    print('-__-')
    print('...')
    print('...')
    print('Press "Ctrl+c"')